config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  match '/users', to: 'users#new', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { maximum: 6 }
  validates :password_confirmation, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = "Invalid Email/Password combination"
      render 'new'
    end
  end
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
  end
  def edit

  end
  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      flash[:success] = "Welcome #{@user.name}"
      redirect_to @user
    else
      flash[:error] = "Sorry there was problem, try again.."
      render 'new'
    end
  end
  def update

  end
  def destroy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'Sample Demo'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag( gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<div class="container">
<footer class="footer navbar-fixed-bottom navbar-inverse">
  <small>
    This demo is developed by <code>Maimit Patel</code>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About Us', '#' %></li>
      <li><%= link_to 'Contact Us', '#' %></li>
    </ul>
  </nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "sample app", root_path , id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Home",    root_path %></li>
            <li><%= link_to "Contact Us",   contact_path %></li>
            <li><%= link_to "About Us", about_path %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key,value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error_explaination">
    <div class="alert alert-error">
      The form contsils <%= pluralize(@user.errors.count, 'error') %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>This is about us page</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>This is Contact page</h1>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Welcome to home page</h1>
  <h2>This is the
    <a href="http://railstutorial.org/">Ruby on Rails tutorial </a> sample Example</h2>
  <%= link_to "Sign Up Now!", new_user_path, class: 'btn btn-large btn-primary' %>
</div>
<%= link_to image_tag("rails.png", alt: 'Rails Image'), 'http://railstutorial.org/' %>

app/views/users/create.html.erb
<h1>Create user</h1>

app/views/users/destroy.html.erb
<h1>Delete User</h1>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

app/views/users/index.html.erb
<h1>All User</h1>

app/views/users/new.html.erb
<% provide(:title, 'New Registration') %>
<div class="row">

  <div class="col-md-5"></div>
  <div class="col-md-7 registration">
    <h3>New Registration?<code>Fill necessary information to join us!</code></h3>
    <%= form_for(@user, :html => {:class => "form-horizontal"}) do |f|  %>
    <%= render 'shared/error_messages' %>
      <div class="form-group">
        <%= f.label :firstName, "First name", :class => "col-sm-3 control-label" %>
        <div class="col-sm-9">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter First Name" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email, "Email", class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :email, class: 'form-control', placeholder: 'Enter Email Address' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password', class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.password_field :password, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, "Retry Password", class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-3"></div>
        <div class="col-md-9">
          <%= f.submit "Create My Account",  class: 'btn btn-large btn-success'%>
        </div>
      </div>



    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide( :title , "#{@user.name} Profile" ) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %><br/>
        <h4>Email: <%= @user.email %></h4>
      </h1>
    </section>
  </aside>
</div>

app/views/users/update.html.erb
<h1>Update User</h1>